apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocketmine.fullname" . }}
  labels:
    {{- include "pocketmine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: minecraftpe
      port: {{ .Values.service.port }}
      targetPort: minecraftpe
      protocol: UDP
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.port)))}}
      nodePort: {{ .Values.service.nodePorts.port }}
      {{- end }}
  selector:
    {{- include "pocketmine.selectorLabels" . | nindent 4 }}
